
source 'https://github.com/CocoaPods/Specs.git'

target 'AACustomDatePicker', :exclusive => true do
  pod "AACustomDatePicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "AACustomDatePicker", :path => "../"

  
end